### ISSUE TITLE
Loading N0G in nmap2 fails

### ISSUE THREAD

**Issue by akrherz** [Unidata/gempak#90] opened 2022-03-28 15:54 UTC
Using a recent GEMPAK, attempting to load N0G in nmap2 results in

>  I tried to look at the super res velocity data (N0G) in NMAP2 and even though the image plotted there was no enhancement table
> associated with it and in the Error button it showed : No entry in imgtyp.tbl.  So not sure what to put in there to get an enhancement 
> table to work.

**Comment by akrherz** [comment] 2022-03-28 16:15
I am unable to reproduce this error at the moment, seeking more clarification from the reporter...

**Comment by sebenste** [comment] 2022-03-29 16:13
I can confirm this issue. Kevin went into imgtyp.tbl and copied the N0Q entry that was in there, duplicated it but then changed it to N0G. At that point, it started plotting, but the colors were off.

**Comment by sebenste** [comment] 2022-06-10 19:13
This has been fixed in 7.15.0. Closing this ticket.

**Comment by sebenste** [comment] 2022-06-10 19:14
Oh, since you opened it, I can't close it. 😁

**Closed** 2022-06-10 20:00 UTC
Labels: bug
